version: "3"
services:
  app:
    build: .
    depends_on:
      - psqldb
    volumes:
      - /home/ayush/Desktop/projects/fastify-prisma:/app
      - /app/node_modules
    ports:
      - "5000:5000"
  psqldb:
    image: "postgres:14-alpine"
    ports:
        - 5433:5432
    volumes:
        - ./db-data/:/var/lib/postgresql/data/
    environment:
        POSTGRES_USER: postgres 
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: fastify-prisma-DB 

