version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    depends_on:
      - psqldb
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - PORT=5001
  psqldb:
    image: "postgres:14-alpine"
    ports:
        - 5433:5432
    volumes:
        - ./db-data/:/var/lib/postgresql/data/
    environment:
        POSTGRES_USER: postgres 
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: fastify-prisma-DB 

